version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 8001
        published: 8001
      - target: 8002
        published: 8002
      - target: 8003
        published: 8003
      - target: 8004
        published: 8004
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
